[package]
name = "dev-garden"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_ascii_terminal = "0.9.1"
bevy_pixel_camera = "0.1.3"
bevy_tiled_camera = "0.3.1"
rand = "0.8.5"
